---
title: Social Interactions and Aggression in Drosophila melanogaster
author:
  - name: Budhaditya Chowdhury
    email: bc036@bucknell.edu
    corresponding: true
    orcid: 0000-0003-3836-0426

---


## Experimental Protocol:

### Materials:

- 2% Agarose
    - *This should be prepared by mixing agarose with water and microwaved till fully dissolved.*
- Clear Corn Syrup
    - *Bought from grocery stores*
- Sugar
- Nipagin / Tegosept
    - *Stock solution made by dissolving 20 grams of tegosept in 100 ml in 95% Ethanol*
- Adult flies (2- day old)
    - *All bottles containing fly genotypes of interest should be kept in an environmentally stable 12hr light/12hr dark conditions. For best results parental flies should not be housed in a crowded condition and transferred to new bottles every 3-5 days. (For best results parental crosses should be set up with 20 virgin females and 20 young males).*
- CO<sub>2</sub> or ice for anesthesia
- [Standard Fly Food](resources.qmd)

### Equipment:

- [3D printed fighting chamber](../protocols/assets/aggression/fighting_chamber.stl)
  - *For best results the chambers should be printed with ABS material at 100-micron thickness.*
- Dividers
  - *For best results X-ray films should be cut with Silhouette printer for accuracy of dimensions.*
- Top glass cover
  - Standard large glass slides, or two regular glass slides placed side by side should be used.
- Base plate for food
  - *Inverted 10 ml clear pipette tip covers can be used as a base plate for food.*
- Computer & Camera setup:
  - Computer for video acquisition and data analysis: *We use a standard Windows PC (Windows 10, 16 GB RAM, 2.6 ghz 4 core processor)*
  - Video acquisition camera body: acA1920-155um \- Basler Ace
  - Video acquisition camera lens: Edmund Industrial Optics 86572 (25mm focal length)
  - 1/4-20" Camera Mounting Plate for Ace Series (Basler 2000029679)
  - USB 3.0 cable ([Basler 2000033239](https://www.digikey.com/short/29vrbv2z))
    - Camera stand (Kaiser Repro Kid Copy Stand Kit (Consists of 23.25" Calibrated Column, 15 x 12.5" Baseboard)
    - LED board for bottom illumination.

### Assembling the Fighting Chamber on food

- Making the food
  - To make food for one divider assay chamber (12 pairs of concurrent fights) the following ingredients and recipe is recommended.
    - Clear corn syrup: 7 mL
      - Sugar: 4 g
      - Agarose: 2 g
      - water: 220 mL
    - Mix all the ingredients in a microwave safe flask and microwave till the food solution runs clear.
    - Let the hot food rest on bench till the temperature falls below 65 C (typically 30 mins or so in room temperature)
    - Add 2 mL Nipagin/Tegosept
    - Pour in food boxes and let it solidify before assembling fighting chamber on top of it (recommended wait time \~2 hours)
- Assembling divider assay chambers on top of food *(Consult Supplementary movie to see the assembly of chamber)*
  - Place three dividers through the slits between the chambers while holding the chamber upside down, supported by the inverted glass cover.
  - Gently move the inverted and assembled fighting chamber up towards the solidified food and once the chamber comes in contact with food surface invert the entire assembly to have a right side up fighting chamber resting on food.

### Loading 2-day old flies on Fighting Chamber

Newly eclosed flies (less than a day old) should be anesthetized on CO2 or ice. Two male flies should be gently placed in a single fighting arena on two sides of the divider. Once 12 pairs have been loaded the top glass cover should be placed on top and secured with a thin strip of clear tape (while not obstructing view of fighting arenas)

### Video acquisition of behavioral experiments

- The divider assay chamber with isolated future fighting pairs should be housed in a temperature and humidity-controlled environment with a 12hr light/12 hr dark cycle.
- Once the flies have reached appropriate age to carry out experiments (5 days) the chamber assembly should be placed under the camera view and on top of LED lightsource for acquisition of high contrast aggression movies.
- The dividers should be gently removed by pulling them out in a linear motion while not disrupting the isolated flies.
- The Basler video acquisition software should be run to acquire movie file of the 12 well chamber for the duration of assay (we recommend recording at 20 Hz, and for assay duration of 20 minutes).
